# Development Docker Compose Configuration
# Egyptian Price Comparison App - Waffar Shokran
version: '3.8'

services:
  # Redis - Shared memory layer for agent coordination
  redis:
    image: redis:7-alpine
    container_name: waffar_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    environment:
      - TZ=Africa/Cairo
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  # Backend - FastAPI with multi-agent scraping
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: waffar_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/__pycache__
    environment:
      - ENVIRONMENT=development
      - REDIS_URL=redis://redis:6379
      - TZ=Africa/Cairo
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
      - LOG_LEVEL=INFO
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - __pycache__/
            - "*.pyc"
            - "*.pyo"
            - "*.pyd"
            - ".pytest_cache/"
            - ".coverage"

  # Frontend - React with Vite
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: waffar_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
      - TZ=Africa/Cairo
    depends_on:
      - backend
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
            - dist/
            - ".vite/"

volumes:
  redis_data:
    driver: local

networks:
  default:
    name: waffar_network